
# Docker-Compose configuration file.

# v3 syntax
version: '3.7'

# Volumes (for persist data when container restart)
volumes:
  # Postgres Data
  playerhunterws-postgres-data:
    driver: local

  # Redis Data
  playerhunterws-redis-data:
    driver: local

# Networks
networks:
  playerhunter:
    name: playerhunter
    driver: bridge

# Services
services:

  # Postgres
  database:
    image: postgres:9.6
    container_name: playerhunter-postgres
    volumes:
      - playerhunterws-postgres-data:/var/lib/pgsql
    networks:
      - playerhunter
    environment:
      - "POSTGRES_DB=playerhunter"
      - "POSTGRES_USER=playerhunter"
      - "POSTGRES_PASSWORD="
    ports:
      - "5433:5432"
    logging:
      driver: none

  # The Application
  app:
    image: ambientum/php:7.2-nginx
    container_name: playerhunter-wapp
    volumes:
      - .:/var/www/app
    networks:
      - playerhunter
    ports:
      - "8000:8080"
    depends_on:
      - database
      - cache